-- Create MEMBER table
CREATE TABLE MEMBERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  join_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  post_count INT NOT NULL DEFAULT 0,
  last_activity DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create CATEGORY table
CREATE TABLE CATEGORIES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  thread_count INT NOT NULL DEFAULT 0,
  post_count INT NOT NULL DEFAULT 0
);

-- Create THREAD table
CREATE TABLE THREADS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category_id INT NOT NULL,
  member_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_post_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  view_count INT NOT NULL DEFAULT 0,
  reply_count INT NOT NULL DEFAULT 0,
  FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id),
  FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);

-- Create POST table
CREATE TABLE POSTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  thread_id INT NOT NULL,
  member_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (thread_id) REFERENCES THREAD(thread_id),
  FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);
