CREATE TABLE `MEMBERS` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(50) UNIQUE NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `login_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `post_count` INT NOT NULL DEFAULT 0,
  `role_id` int NOT NULL DEFAULT 1
);

CREATE TABLE `CATEGORIES` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT,
  `thread_count` INT NOT NULL DEFAULT 0,
  `post_count` INT NOT NULL DEFAULT 0
);

CREATE TABLE `THREADS` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `last_post_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `view_count` INT NOT NULL DEFAULT 0,
  `reply_count` INT NOT NULL DEFAULT 0
);

CREATE TABLE `POSTS` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `thread_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE `Roles` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT
);

ALTER TABLE `THREADS` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORIES` (`id`);

ALTER TABLE `THREADS` ADD FOREIGN KEY (`member_id`) REFERENCES `MEMBERS` (`id`);

ALTER TABLE `POSTS` ADD FOREIGN KEY (`thread_id`) REFERENCES `THREADS` (`id`);

ALTER TABLE `POSTS` ADD FOREIGN KEY (`member_id`) REFERENCES `MEMBERS` (`id`);

ALTER TABLE `MEMBERS` ADD FOREIGN KEY (`role_id`) REFERENCES `Roles` (`id`);
